export interface PlayerConfig {
  code: string;
  province: string;
}

export const PLAYERS: PlayerConfig[] = [
  // Ontario
  { code: "PTBO#289",   province: "ON" },
  { code: "MGMG#288",   province: "ON" },
  { code: "ERIK#300",   province: "ON" },
  { code: "FUGU#591",   province: "ON" },
  { code: "MON#0",      province: "ON" },
  { code: "DRIO#631",   province: "ON" },
  { code: "WEEG#0",     province: "ON" },
  { code: "TPN#918",    province: "ON" },
  { code: "QUIG#162",   province: "ON" },
  { code: "GOOS#584",   province: "ON" },
  { code: "VBS#776",    province: "ON" },
  { code: "JOEY#149",   province: "ON" },
  { code: "BRGR#785",   province: "ON" },
  { code: "JSTN#404",   province: "ON" },
  { code: "XEON#914",   province: "ON" },
  { code: "BRUH#696",   province: "ON" },
  { code: "TORA#0",     province: "ON" },
  { code: "ERIC#108",   province: "ON" },
  { code: "TOMB#572",   province: "ON" },
  { code: "POOP#732",   province: "ON" },
  { code: "GRAPE#0",    province: "ON" },
  { code: "SAL#574",    province: "ON" },
  { code: "MIST#720",   province: "ON" },
  { code: "CHET#349",   province: "ON" },
  { code: "OTES#443",   province: "ON" },
  { code: "SHAD#749",   province: "ON" },
  { code: "TROP#801",   province: "ON" },
  { code: "FIVE#0",     province: "ON" },
  { code: "CHRS#722",   province: "ON" },
  { code: "XARI#950",   province: "ON" },
  { code: "SIXTY#40",   province: "ON" },
  { code: "BLOW#471",   province: "ON" },
  { code: "SONO#131",   province: "ON" },
  { code: "BOOTS#0",    province: "ON" },
  { code: "VIET#598",   province: "ON" },
  { code: "WAVE#266",   province: "ON" },
  { code: "BAN#376",    province: "ON" },
  { code: "GOOP#830",   province: "ON" },
  { code: "CHEESE#0",   province: "ON" },
  { code: "MACK#891",   province: "ON" },
  { code: "RC#412",     province: "ON" },
  { code: "CS#404",     province: "ON" },
  { code: "HAMR#281",   province: "ON" },
  { code: "YON#371",    province: "ON" },
  { code: "SCHW#842",   province: "ON" },
  { code: "JPLM#709",   province: "ON" },
  { code: "RICE#192",   province: "ON" },
  { code: "MILK#255",   province: "ON" },
  { code: "NDOC#204",   province: "ON" },
  { code: "LOAM#886",   province: "ON" },
  { code: "BSKN#686",   province: "ON" },
  { code: "DUB#288",    province: "ON" },
  { code: "OODE#924",   province: "ON" },
  { code: "CHOC#536",   province: "ON" },
  { code: "BURN#324",   province: "ON" },
  { code: "MXP#200",    province: "ON" },
  { code: "COST#566",   province: "ON" },
  { code: "BAGG#730",   province: "ON" },
  { code: "CUMM#826",   province: "ON" },
  { code: "SNPE#373",   province: "ON" },
  { code: "YEET#764",   province: "ON" },
  { code: "AIDA#550",   province: "ON" },
  { code: "PHEM#652",   province: "ON" },
  { code: "MIRA#750",   province: "ON" },
  { code: "SKYE#361",   province: "ON" },
  { code: "JCHI#699",   province: "ON" },
  { code: "HD#811",     province: "ON" },
  { code: "CHUM#604",   province: "ON" },
  { code: "SICK#0",     province: "ON" },
  { code: "JAYY#420",   province: "ON" },
  { code: "LOBL#140",   province: "ON" },
  { code: "BONG#391",   province: "ON" },
  { code: "BOJA#432",   province: "ON" },
  { code: "SWFT#172",   province: "ON" },
  { code: "CHEB#984",   province: "ON" },
  { code: "FLIP#604",   province: "ON" },
  { code: "PIXZ#154",   province: "ON" },
  { code: "TSK#895",    province: "ON" },
  { code: "LEON#897",   province: "ON" },
  { code: "CMDB#727",   province: "ON" },
  { code: "RSQ#388",    province: "ON" },
  { code: "QUAN#950",   province: "ON" },
  { code: "SUPE#409",   province: "ON" },
  { code: "SUBS#758",   province: "ON" },
  { code: "ZAP#475",    province: "ON" },
  { code: "CASH#393",   province: "ON" },
  { code: "SLIP#770",   province: "ON" },
  { code: "BOWSER#0",   province: "ON" },
  { code: "RMZ#564",    province: "ON" },
  { code: "MOSH#703",   province: "ON" },
  { code: "LEMON#72",   province: "ON" },
  { code: "WARD#537",   province: "ON" },
  { code: "GRIF#463",   province: "ON" },
  { code: "AIDS#321",   province: "ON" },
  { code: "LULW#001",   province: "ON" },
  { code: "CHICH#0",    province: "ON" },
  { code: "AJ#387",     province: "ON" },
  { code: "V#1",        province: "ON" },
  { code: "THED#802",   province: "ON" },
  { code: "ALLE#841",   province: "ON" },
  { code: "DARR#436",   province: "ON" },
  { code: "RABB#371",   province: "ON" },
  { code: "MFSA#435",   province: "ON" },
  { code: "PHORKY#0",   province: "ON" },
  { code: "TOFF#64",    province: "ON" },
  { code: "FROG#115",   province: "ON" },
  { code: "DUSD#547",   province: "ON" },
  { code: "COZY#304",   province: "ON" },
  { code: "TKTL#644",   province: "ON" },
  { code: "ZUPPY#0",    province: "ON" },
  { code: "SPWT#231",   province: "ON" },
  { code: "NEO#614",    province: "ON" },
  { code: "BALA#957",   province: "ON" },
  { code: "UNIT#02",    province: "ON" },
  { code: "SCOUT#69",   province: "ON" },
  { code: "FITZ#69",    province: "ON" },
  { code: "MOKY#475",   province: "ON" },
  { code: "SPAM#376",   province: "ON" },
  { code: "ZEEK#153",   province: "ON" },
  { code: "SUNR#250",   province: "ON" },
  { code: "SOUR#240",   province: "ON" },
  { code: "PARA#784",   province: "ON" },
  { code: "ZANG#450",   province: "ON" },
  { code: "EMLY#878",   province: "ON" },
  { code: "SEEN#906",   province: "ON" },
  { code: "REST#867",   province: "ON" },
  { code: "DSMASH#0",   province: "ON" },
  { code: "SEVAN#0",    province: "ON" },
  { code: "WOOD#762",   province: "ON" },
  { code: "FURA#694",   province: "ON" },
  { code: "LIME#200",   province: "ON" },
  { code: "BMMT#894",   province: "ON" },
  { code: "NINO#845",   province: "ON" },
  { code: "ROM#443",    province: "ON" },
  { code: "OQUI#822",   province: "ON" },
  { code: "JIZZ#560",   province: "ON" },
  { code: "PAYT#635",   province: "ON" },
  { code: "PORK#643",   province: "ON" },
  { code: "DLAY#650",   province: "ON" },
  { code: "BUIG#156",   province: "ON" },
  { code: "COLD#481",   province: "ON" },
  { code: "CG#0",       province: "ON" },
  { code: "KAR#513",    province: "ON" },
  { code: "TREV#215",   province: "ON" },
  { code: "ANDY#741",   province: "ON" },
  { code: "CDOE#570",   province: "ON" },
  { code: "CLNT#716",   province: "ON" },
  { code: "ZEE#0",      province: "ON" },
  { code: "MOSH#823",   province: "ON" },
  { code: "LORD#522",   province: "ON" },
  { code: "RALC#865",   province: "ON" },
  { code: "SEPH#142",   province: "ON" },
  { code: "VICE#93",    province: "ON" },
  { code: "DOPE#0",     province: "ON" },
  { code: "BUBS#861",   province: "ON" },
  { code: "WOOP#775",   province: "ON" },
  { code: "CHBL#359",   province: "ON" },
  { code: "BETA#291",   province: "ON" },
  { code: "FAIZ#836",   province: "ON" },
  { code: "SIXT#368",   province: "ON" },
  { code: "FALCO#1",    province: "ON" },
  { code: "SWAT#943",   province: "ON" },
  { code: "SHORTS#0",   province: "ON" },
  { code: "MARK#783",   province: "ON" },
  { code: "CSTR#106",   province: "ON" },
  { code: "2FLY#0",     province: "ON" },
  { code: "TOP#495",    province: "ON" },
  { code: "MONK#565",   province: "ON" },
  { code: "ASB#620",    province: "ON" },
  { code: "NIX#0",      province: "ON" },
  { code: "INOX#135",   province: "ON" },
  { code: "PLAT#817",   province: "ON" },
  { code: "MAR#10",     province: "ON" },
  { code: "ZULF#268",   province: "ON" },
  { code: "CHUFF#0",    province: "ON" },
  { code: "ALOE#430",   province: "ON" },
  { code: "BEAN#143",   province: "ON" },
  { code: "LUM#1",      province: "ON" },
  { code: "PAMY#283",   province: "ON" },
  { code: "MICH#316",   province: "ON" },
  { code: "CLOC#573",   province: "ON" },
  { code: "NMFC#0",     province: "ON" },
  { code: "LEEROY#0",   province: "ON" },
  { code: "JB#901",     province: "ON" },
  { code: "FADE#840",   province: "ON" },
  { code: "ACSL#101",   province: "ON" },
  { code: "HUND#100",   province: "ON" },
  { code: "RENE#413",   province: "ON" },
  { code: "LQD#160",    province: "ON" },
  { code: "KATA#963",   province: "ON" },
  { code: "SLIM#768",   province: "ON" },
  { code: "TEN#10",     province: "ON" },
  { code: "WAVE#548",   province: "ON" },
  { code: "INFE#106",   province: "ON" },
  { code: "JUST#370",   province: "ON" },
  { code: "HAX#0",      province: "ON" },
  { code: "LOG#902",    province: "ON" },
  { code: "PENN#0",     province: "ON" },
  { code: "GOML#617",   province: "ON" },
  { code: "PRIN#916",   province: "ON" },
  { code: "DEER#367",   province: "ON" },
  { code: "MKRL#970",   province: "ON" },
  { code: "MILE#664",   province: "ON" },
  { code: "DRES#335",   province: "ON" },
  { code: "PZZA#137",   province: "ON" },
  { code: "LEAF#419",   province: "ON" },
  { code: "DG#837",     province: "ON" },
  { code: "ARBUST#0",   province: "ON" },
  { code: "LDW#174",    province: "ON" },
  { code: "ZW#679",     province: "ON" },
  { code: "INVA#556",   province: "ON" },
  { code: "MATT#475",   province: "ON" },
  { code: "ASTE#267",   province: "ON" },
  { code: "BAKE#242",   province: "ON" },
  { code: "UNCL#225",   province: "ON" },
  { code: "DRNT#0",     province: "ON" },
  { code: "KERR#567",   province: "ON" },
  { code: "AZUR#889",   province: "ON" },
  { code: "DTR#451",    province: "ON" },
  { code: "STOC#507",   province: "ON" },
  { code: "SHPX#987",   province: "ON" },
  { code: "GAHR#668",   province: "ON" },
  { code: "TOKI#0",     province: "ON" },
  { code: "REMO#405",   province: "ON" },

  // Quebec
  { code: "OLIP#180",   province: "QC" },
  { code: "CM#296",     province: "QC" },
  { code: "SEB#949",    province: "QC" },
  { code: "BTW#894",    province: "QC" },
  { code: "HGOD#424",   province: "QC" },
  { code: "SQUI#551",   province: "QC" },
  { code: "LEXI#321",   province: "QC" },
  { code: "FED#659",    province: "QC" },
  { code: "FROG#532",   province: "QC" },
  { code: "FCBD#314",   province: "QC" },
  { code: "DROU#378",   province: "QC" },
  { code: "BOO#862",    province: "QC" },
  { code: "DM#678",     province: "QC" },
  { code: "TT#999",     province: "QC" },
  { code: "MORO#730",   province: "QC" },
  { code: "MARK#567",   province: "QC" },
  { code: "TIBE#0",     province: "QC" },
  { code: "SICCA#0",    province: "QC" },
  { code: "EAGL#248",   province: "QC" },
  { code: "KOU#893",    province: "QC" },
  { code: "ZEDU#940",   province: "QC" },
  { code: "PNGU#578",   province: "QC" },
  { code: "MFRT#153",   province: "QC" },
  { code: "PICH#234",   province: "QC" },
  { code: "MOB#196",    province: "QC" },

  // Nova Scotia
  { code: "TEST#502",   province: "NS" },
  { code: "LILM#141",   province: "NS" },
  { code: "INKY#398",   province: "NS" },
  { code: "KAY#0",      province: "NS" },
  { code: "KI#0",       province: "NS" },
  { code: "ALDU#300",   province: "NS" },
  { code: "CRAB#117",   province: "NS" },
  { code: "KING#244",   province: "NS" },
  { code: "SUPE#824",   province: "NS" },
  { code: "POST#647",   province: "NS" },
  { code: "JOKA#636",   province: "NS" },
  { code: "SPKY#115",   province: "NS" },
  { code: "CODE#0",     province: "NS" },
  { code: "BLNS#710",   province: "NS" },
  { code: "BURN#482",   province: "NS" },
  { code: "RAIN#354",   province: "NS" },
  { code: "BRAD#666",   province: "NS" },
  { code: "FROG#0",     province: "NS" },
  { code: "CLUM#955",   province: "NS" },
  { code: "JOHN#697",   province: "NS" },
  { code: "PAL#585",    province: "NS" },
  { code: "WEEM#844",   province: "NS" },
  { code: "WEEM#543",   province: "NS" },
  { code: "PEPE#223",   province: "NS" },
  { code: "GLUMB#0",    province: "NS" },
  { code: "DAYM#666",   province: "NS" },
  { code: "THRN#111",   province: "NS" },
  { code: "PPMD#0",     province: "NS" },
  { code: "YQI#927",    province: "NS" },

  // Newfoundland & Labrador
  { code: "SHUG#957",   province: "NL" },
  { code: "NUSS#902",   province: "NL" },
  { code: "QWIZ#159",   province: "NL" },
  { code: "OURO#629",   province: "NL" },
  { code: "SAND#468",   province: "NL" },
  { code: "KOIL#0",     province: "NL" },
  { code: "POOP#818",   province: "NL" },
  { code: "PINE#594",   province: "NL" },
  { code: "KIP#0",      province: "NL" },
  { code: "JOEL#298",   province: "NL" },
  { code: "CAP#769",    province: "NL" },
  { code: "LUHG#333",   province: "NL" },
  { code: "KAIJU#0",    province: "NL" },
  { code: "GLTY#837",   province: "NL" },
  { code: "NGO#151",    province: "NL" },
  { code: "PAIN#726",   province: "NL" },
  { code: "KZ#0",       province: "NL" },
  { code: "WOO#113",    province: "NL" },
  { code: "BTM#879",    province: "NL" },
  { code: "RF#653",     province: "NL" },
  { code: "HFAM#261",   province: "NL" },
  { code: "JSHY#307",   province: "NL" },
  { code: "BAE#0",      province: "NL" },
  { code: "CLOUT#0",    province: "NL" },
  { code: "ABS#609",    province: "NL" },
  { code: "SAG#537",    province: "NL" },
  { code: "DRYN#589",   province: "NL" },

  // Alberta
  { code: "DOBY#705",   province: "AB" },
  { code: "FALC#784",   province: "AB" },
  { code: "AUJO#939",   province: "AB" },
  { code: "MAMA#623",   province: "AB" },
  { code: "ZOOK#355",   province: "AB" },
  { code: "SOON#122",   province: "AB" },
  { code: "WATE#414",   province: "AB" },
  { code: "LIPS#618",   province: "AB" },
  { code: "REBO#142",   province: "AB" },
  { code: "LEGY#920",   province: "AB" },
  { code: "MM#456",     province: "AB" },
  { code: "ENEN#890",   province: "AB" },
  { code: "EGGS#234",   province: "AB" },
  { code: "ODIN#0",     province: "AB" },
  { code: "RATS#141",   province: "AB" },
  { code: "KNEE#860",   province: "AB" },
  { code: "SWAG#567",   province: "AB" },
  { code: "PAT#0",      province: "AB" },
  { code: "AMANDA#0",   province: "AB" },
  { code: "ANJO#265",   province: "AB" },
  { code: "FIJI#516",   province: "AB" },
  { code: "DRFT#691",   province: "AB" },
  { code: "POWE#735",   province: "AB" },
  { code: "THG#177",    province: "AB" },
  { code: "HAIR#23",    province: "AB" },
  { code: "WILL#370",   province: "AB" },
  { code: "DAZ#0",      province: "AB" },
  { code: "AP#0",       province: "AB" },
  { code: "KRNS#750",   province: "AB" },
  { code: "TMPT#69",    province: "AB" },
  { code: "VEN#123",    province: "AB" },
  { code: "ENBY#825",   province: "AB" },
  { code: "JRAFF#0",    province: "AB" },
  { code: "SCHU#432",   province: "AB" },
  { code: "WADU#291",   province: "AB" },
  { code: "SOR#182",    province: "AB" },
  { code: "KASE#672",   province: "AB" },
  { code: "GGWP#161",   province: "AB" },
  { code: "DINO#565",   province: "AB" },
  { code: "HIME#0",     province: "AB" },
  { code: "KEVIN#01",   province: "AB" },
  { code: "MM#491",     province: "AB" },
  { code: "DIB#1",      province: "AB" },
  { code: "YYCG#448",   province: "AB" },

  // Manitoba
  { code: "VMAN#920",   province: "MB" },
  { code: "DRIGHT#1",   province: "MB" },
  { code: "CRUZ#0",     province: "MB" },
  { code: "CHSE#180",   province: "MB" },
  { code: "STRK#533",   province: "MB" },
  { code: "POMP#831",   province: "MB" },
  { code: "AMY#672",    province: "MB" },
  { code: "THOR#829",   province: "MB" },
  { code: "BAND#442",   province: "MB" },
  { code: "FBRZ#401",   province: "MB" },
  { code: "GOGH#920",   province: "MB" },
  { code: "BLUB#409",   province: "MB" },
  { code: "PKJT#617",   province: "MB" },
  { code: "WINDS#01",   province: "MB" },
  { code: "JOEZ#583",   province: "MB" },
  { code: "THRI#632",   province: "MB" },
  { code: "KIRO#903",   province: "MB" },
  { code: "ANGUS#0",    province: "MB" },

  // Saskatchewan
  { code: "BZF#1",      province: "SK" },
  { code: "SCRUNK#0",   province: "SK" },
  { code: "JESS#405",   province: "SK" },
  { code: "SYMB#384",   province: "SK" },
  { code: "CELL#0",     province: "SK" },
  { code: "MIKEAL#0",   province: "SK" },
  { code: "MUX#711",    province: "SK" },
  { code: "SLEE#871",   province: "SK" },
  { code: "SHOR#710",   province: "SK" },
  { code: "RFST#177",   province: "SK" },
  { code: "FALL#13",    province: "SK" },
  { code: "WGOD#456",   province: "SK" },
  { code: "GWK#466",    province: "SK" },
  { code: "BLB#773",    province: "SK" },
  { code: "SGA#222",    province: "SK" },
  { code: "MISS#4",     province: "SK" },
  { code: "TUBA#262",   province: "SK" },
  { code: "SHAW#907",   province: "SK" },
  { code: "LONE#872",   province: "SK" },

  // British Columbia
  { code: "BABA#773",   province: "BC" },
  { code: "DHIR#906",   province: "BC" },
  { code: "GREY#564",   province: "BC" },
  { code: "FROI#180",   province: "BC" },
  { code: "ELNO#923",   province: "BC" },
  { code: "AMSA#0",     province: "BC" },
  { code: "C#4",        province: "BC" },
  { code: "ADAM#777",   province: "BC" },
  { code: "TECHN#0",    province: "BC" },
  { code: "VENX#957",   province: "BC" },
  { code: "MTRX#833",   province: "BC" },
  { code: "ZEDD#556",   province: "BC" },
  { code: "TRAD#394",   province: "BC" },

  // New Brunswick
  { code: "DRIZZY#8",   province: "NB" },
  { code: "MAC#891",    province: "NB" },
  { code: "BRUH#69",    province: "NB" },
  { code: "SLOP#226",   province: "NB" },
  { code: "EAST#911",   province: "NB" },
  { code: "ADAM#630",   province: "NB" },
  { code: "POLY#688",   province: "NB" },
  { code: "APE#608",    province: "NB" },
  { code: "TEST#494",   province: "NB" },
  { code: "HYPR#171",   province: "NB" },

  // Prince Edward Island
  { code: "AJC#752",    province: "PE" },
  { code: "TYUI#645",   province: "PE" },
  { code: "MIND#228",   province: "PE" },

  // Yukon
  { code: "DAVE#815",   province: "YT" },

  // Nunavut
  { code: "SLAY#747",   province: "NU" },
];

export const LEADERBOARD_TITLE = "Canada Slippi Leaderboard";
export const LEADERBOARD_REGION = "Canada";

export const PROVINCE_COLORS: Record<string, { text: string; bg: string; border: string }> = {
  ON: { text: "#60a5fa", bg: "#60a5fa22", border: "#60a5fa55" },
  QC: { text: "#a78bfa", bg: "#a78bfa22", border: "#a78bfa55" },
  BC: { text: "#34d399", bg: "#34d39922", border: "#34d39955" },
  AB: { text: "#fbbf24", bg: "#fbbf2422", border: "#fbbf2455" },
  MB: { text: "#f472b6", bg: "#f472b622", border: "#f472b655" },
  SK: { text: "#fb923c", bg: "#fb923c22", border: "#fb923c55" },
  NS: { text: "#38bdf8", bg: "#38bdf822", border: "#38bdf855" },
  NB: { text: "#4ade80", bg: "#4ade8022", border: "#4ade8055" },
  NL: { text: "#e879f9", bg: "#e879f922", border: "#e879f955" },
  PE: { text: "#f87171", bg: "#f8717122", border: "#f8717155" },
  YT: { text: "#facc15", bg: "#facc1522", border: "#facc1555" },
  NT: { text: "#94a3b8", bg: "#94a3b822", border: "#94a3b855" },
  NU: { text: "#c084fc", bg: "#c084fc22", border: "#c084fc55" },
};

export const PROVINCE_NAMES: Record<string, string> = {
  BC: "British Columbia",
  AB: "Alberta",
  SK: "Saskatchewan",
  MB: "Manitoba",
  ON: "Ontario",
  QC: "Quebec",
  NB: "New Brunswick",
  NS: "Nova Scotia",
  PE: "Prince Edward Island",
  NL: "Newfoundland",
  YT: "Yukon",
  NT: "Northwest Territories",
  NU: "Nunavut",
};
